
#initial Analysis

```{r p1,cache=TRUE,echo=TRUE,warning=FALSE,message=FALSE,error=FALSE,eval=FALSE}

# Reading the raw CSV file
raw_data<-read.csv("./uptake_new/testingCandidate.csv",header=TRUE) 

#checking class of each variable
lapply(raw_data,class)


 #checking propotion of NA values for  each variable
sapply(raw_data,function(x) (sum(is.na(x))))  


#Function to count NA's or unknown value in each column  
countNA<-function(data){
  df<-data.frame(matrix(ncol=ncol(raw_data),nrow=2))
  colnames(df)<-colnames(data)
  for ( i in 1:ncol(data)){
    
    missing=0
    for ( j in 1:nrow(data)){
      #print(j)
      #print(data[j,i])
      if (is.na(data[j,i])| data[j,i]=="unknown"){
        missing=missing+1
      }
      }
    df[1,i]<-missing
    df[2,i]<-round((missing/nrow(data))*100,digits=2)
    }
    rownames(df)<-c("Total Missing","Percentage missing")
    return (df)
  }

```  


##Imputing Missing Data
```{r  p2,cache=TRUE,echo=TRUE,warning=FALSE,message=FALSE,error=FALSE,eval=FALSE } 

#Function to change unknown values to NA Values (Helpful during imputation) 
replaceUnknown<-function(data){
  df<-data
  for ( i in 1:ncol(df)){
    for ( j in 1:nrow(df)){
         if (!is.na(df[j,i]) && df[j,i]=="unknown"){
           df[j,i]<-NA
         }
      }
    }
    
    return (df)
  }

library(Hmisc) #Used for imputation of missing values. 
library(missForest)
data_NA<-replaceUnknown(raw_data)
data_NA.imp<-missForest(data_NA,maxiter=1,ntree=10) 
write.csv(data_NA.imp$ximp,file="impute_testingCandidate.csv")

``` 










